version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 4000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./dashboards:/etc/grafana/provisioning/dashboards/
      # - ./datasources:/etc/grafana/provisioning/datasources/
      # - ./folders:/etc/grafana/provisioning/folders/
      - ./configs/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./configs/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./dashboards/node-metrics.json:/var/lib/grafana/dashboards/node-metrics.json
      - ./dashboards/container-metrics.json:/var/lib/grafana/dashboards/container-metrics.json

    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,golioth-websocket-datasource,volkovlabs-echarts-panel,marcusolsson-json-datasource,yesoreyeram-infinity-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/container-metrics.json

volumes:
  grafana_data: